### ISSUE TITLE
Taxonomy to contribute for the official MISP taxonomy repository?

### ISSUE THREAD

**Issue by adulau** [thalesgroup-cert/Thalesgroup-misp-taxonomy#2]
The taxonomy sounds interesting and it could be useful to have it in MISP default taxonomy repository:

- It could be used as an example for other organisations;
- It could ease the installation for Thales users as it will be part of the default MISP taxonomy repository.

Feel free to make  a pull-request on  [https://github.com/MISP/misp-taxonomies](https://github.com/MISP/misp-taxonomies)

**Comment by Felix83000** [comment]
Great idea! 

We will be more than happy to contribute!
Yes indeed, it will be much easier for Thales users. 👍  

Thank you Alexandre!

**Comment by adulau** [comment]
Thank you very much for the PR. It’s now merged.
